### ISSUE TITLE
Laravel Scout 6.0 is available

### ISSUE THREAD

**Issue by znsstudio** [worksweet/laravel-scout-mysql-driver#75]
Installed 6.0 and than try this package got with error

https://github.com/YABhq/laravel-scout-mysql-driver/blob/b039768cdcec690135d3c9853fdff844f1d1d8ad/composer.json#L19

**Comment by z-h-z-h** [comment]
How to fix that?

**Comment by manshu** [comment]
Is this updated yet ?

**Comment by msonowal** [comment]
Its updated
